export const GET_FORM_REQUEST = "GET_FORM_REQUEST";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";

export const UPDATE_PROJECT_FORM_DATA = 'UPDATE_PROJECT_FORM_DATA';