export const HANDLE_DRAWER_TOGGLE_CHANGE = "HANDLE_DRAWER_TOGGLE_CHANGE";

export const GET_FORM_REQUEST = "GET_FORM_REQUEST";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";
export const CREATE_FORM_REQUEST="CREATE_FORM_REQUEST";
export const CREATE_FORM_SUCCESS="CREATE_FORM_SUCCESS";
export const CREATE_FORM_FAILURE="CREATE_FORM_FAILURE";
export const DELETE_FORM_REQUEST="DELETE_FORM_REQUEST";
export const DELETE_FORM_SUCCESS= "DELETE_FORM_SUCCESS";
export const DELETE_FORM_FAILURE= "DELETE_FORM_FAILURE";
export const UPDATE_FORM_REQUEST= "UPDATE_FORM_REQUEST";
export const UPDATE_FORM_SUCCESS= "UPDATE_FORM_SUCCESS";
export const UPDATE_FORM_FAILURE= "UPDATE_FORM_FAILURE";
